### PR TITLE
Make date picker usable

### PR DESCRIPTION
**Pull request by betty-alagwu**
This PR is the first pass for issue #5452

This PR uses the right component styling for the datePicker

here's a video of how it works

https://github.com/highlight/highlight/assets/94234459/75f0de6a-65f7-4191-a49b-61198b49b1a0

### CODE REVIEW

**Comment by betty-alagwu** [comment]
Hey @julian-highlight thanks for the feedback.

Regarding the first suggestion, to prevent the hover effect from being applied to the disabled date, I think its a great idea. 

Actually, I was considering implementing this.
I'll go ahead and implement it right away

Also thanks for sharing the Airbnb example, I'll reference it for the next updates I'll be doing.

**Comment by betty-alagwu** [comment]
Hello @julian-highlight I just made some changes and here's how it works now, please share your feedback when you get the chance.


https://github.com/highlight/highlight/assets/94234459/099fffa7-2065-4e83-8e6e-bf258c510098

**Review by jay-khatri — APPROVED** [review]
This looks great to me product-wise. Will defer to @ccschmitz on a code review.

**Comment by Vadman97** [comment]
@betty-alagwu you'll need to run `yarn reflame-build` (as seen in the [test details](https://github.com/highlight/highlight/actions/runs/5193142945/jobs/9363275093?pr=5535)) to get the build to pass

**Comment by betty-alagwu** [comment]
> @betty-alagwu you'll need to run `yarn reflame-build` (as seen in the [test details](https://github.com/highlight/highlight/actions/runs/5193142945/jobs/9363275093?pr=5535)) to get the build to pass

Thank you @Vadman97  the checks are running successfully now.

**Review by Vadman97 — APPROVED** [review]
thanks! code changes look good based on [preview ](https://preview.highlight.io/1/sessions?page=1&query=and%7C%7Ccustom_created_at%2Cbetween_date%2C2023-05-31T16%3A31%3A20.622Z_2023-06-07T16%3A31%3A20.465Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22sjc%22%2C%22variantId%22%3A%2201H2628NZ0YAAAGNW2PA6FT8KW%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22make-datePicker-usable%5C%22%2C%5C%22forkSpecifier%5C%22%3A%5C%22betty-alagwu%2Fhighlight%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)

**Pull request merged**
