### PR TITLE
fix: Twitter logo not updated 

### PR DESCRIPTION
**Pull request by lalitkumawat1m**
## Summary

Closes: #6488

Changed Old Twitter logo to new X logo

## How did you test this change?

Locally

## Does this work require review from our design team?

Yes

### CODE REVIEW

**Review by mayberryzane — CHANGES_REQUESTED** [review]
Thanks for updating this! To be consistent with our use of FontAwesome icons for Github / LinkedIn, could we change this to use the new `FaXTwitter` icon from there instead?

https://react-icons.github.io/react-icons/icons?name=fa6

**Comment by lalitkumawat1m** [comment]
sure i will update this

**Review by mayberryzane — APPROVED** [review]
Thanks @lalitkumawat1m - code changes look good to me, I'll work through the remaining build issues and get this deployed today

**Review by julian-highlight — APPROVED** [review]

**Comment by Vadman97** [comment]
```
Checking formatting...
[warn] highlight.io/components/common/Footer/Footer.tsx
[warn] Code style issues found in the above file. Forgot to run Prettier?
```

@lalitkumawat1m mind running `yarn format:all` to fix the lint error? looks good other than that!

**Comment by Vadman97** [comment]
bump @lalitkumawat1m

**Comment by Vadman97** [comment]
bump @lalitkumawat1m

**Comment by Vadman97** [comment]
bump @lalitkumawat1m

**Pull request merged**
