### PR TITLE
Cleanup Java SDK

### PR DESCRIPTION
**Pull request by NgLoader**
chore: cleanup some classes
fix: code spacing in some classes

## Summary
Cleanup the java sdk and add some missing commands.
Also made the ``servername`` optionaly.

## How did you test this change?
Localy

## Are there any deployment considerations?
No

## Does this work require review from our design team?
No

### CODE REVIEW

**Review by Vadman97 — APPROVED** [review]
looks good so far!

**Comment by NgLoader** [comment]
Hey, sry for the delay at first im done.
Need to do some other work first but soon I will commit some new implementations (framework / logger support) in java.

**Comment by Vadman97** [comment]
@NgLoader could you please rebase on main so we can update the checks and merge?

**Pull request merged**
