### PR TITLE
update pricing page

### PR DESCRIPTION
**Pull request by Vadman97**
## Summary

Reflect new graduated pricing model on highlight.io/pricing

Screenshot 2023-11-18 at 7 26 38 PM

image

Screenshot 2023-11-21 at 11 45 13 PM

## How did you test this change?

[Vercel preview](https://highlight-landing-git-vadim-pricing-landing-highlight-run.vercel.app/pricing).

## Are there any deployment considerations?

No

## Does this work require review from our design team?

No

### CODE REVIEW

**Comment by jay-khatri** [comment]
Does this include the $50 tier?

**Comment by jay-khatri** [comment]
Can we make the range for logs/traces 0 -> 5b or something? Right now, the max price you can pay is quite low.

image

**Comment by mayberryzane** [comment]
do we want 50m traces included for free? I think it's 1m in the app at the moment because I copied what we had for logs

**Comment by Vadman97** [comment]
> Does this include the $50 tier?

updated to include the base fee and updated slider ranges
for free tier, number of traces is increased per [slack thread](https://highlightcorp.slack.com/archives/C0454PWLLLW/p1700509687085739)

**Review by mayberryzane — APPROVED** [review]

**Pull request merged**
