### PR TITLE
Add position indicator in session logs

### LINKED ISSUE #4872: Add position indicator in session logs
https://github.com/highlight/highlight/pull/6303 added a visual indicator for errors and network resources, and we'd like to add a similar indicator for console logs.

### PR DESCRIPTION
**Pull request by syedbarimanjan**
## Summary
closes #4872 
/claim #4872
I noticed that the arrow icon in the network logs doesn't function, whereas it works as a 'go-to' button in error logs. Is this intentional or does it need fixing?
I also noticed that when switching tabs, if I'm at a certain timestamp in one tab and then switch to another tab, the new tab doesn't automatically scroll to the current active log.(By tab i mean console, error and network tabs)
[Screencast from 17-04-2024 10:58:45.webm](https://github.com/highlight/highlight/assets/112156147/8d35835e-14d1-4584-a32c-ac59886fa6d3)

## How did you test this change?
[Screencast from 17-04-2024 10:27:46.webm](https://github.com/highlight/highlight/assets/112156147/45d0e7b7-e476-4f3a-87bd-24e495952177)

## Are there any deployment considerations?
None

## Does this work require review from our design team?
No

### CODE REVIEW

**Comment by syedbarimanjan** [comment]
@et @Vadman97 could you review.

**Review by Vadman97 — APPROVED** [review]
preview looks great! thank you for your contribution

> I noticed that the arrow icon in the network logs doesn't function, whereas it works as a 'go-to' button in error logs. Is this intentional or does it need fixing?

not intentional - would you mind helping fix this?

> I also noticed that when switching tabs, if I'm at a certain timestamp in one tab and then switch to another tab, the new tab doesn't automatically scroll to the current active log.(By tab i mean console, error and network tabs)

yup, i see that as well. would be great to fix that - looks like some `useEffect` needs to fix on tab change to trigger a scroll on tab change?

**Comment by syedbarimanjan** [comment]
> preview looks great! thank you for your contribution
> 
> > I noticed that the arrow icon in the network logs doesn't function, whereas it works as a 'go-to' button in error logs. Is this intentional or does it need fixing?
> 
> not intentional - would you mind helping fix this?
> 
> > I also noticed that when switching tabs, if I'm at a certain timestamp in one tab and then switch to another tab, the new tab doesn't automatically scroll to the current active log.(By tab i mean console, error and network tabs)
> 
> yup, i see that as well. would be great to fix that - looks like some `useEffect` needs to fix on tab change to trigger a scroll on tab change?

Should i create a seperate pr for these or just do them here?

**Comment by syedbarimanjan** [comment]
I will make the changes today.

**Comment by syedbarimanjan** [comment]
@Vadman97 as this is approved can you merge it I will create a new pr for the changes.

**Comment by Vadman97** [comment]
@syedbarimanjan can you run yarn format:all to fix the lint errors?

**Comment by syedbarimanjan** [comment]
> @syedbarimanjan can you run yarn format:all to fix the lint errors?

Did it

**Comment by syedbarimanjan** [comment]
@Vadman97

**Comment by syedbarimanjan** [comment]
@Vadman97

**Comment by syedbarimanjan** [comment]
@Vadman97

**Comment by syedbarimanjan** [comment]
@Vadman97 I would like to further contribute to the project but most of the issues are created by a bot which is making it hard to pick an issue.

**Pull request merged**
