### PR TITLE
Move mentions classname to scss module, rearrange classes

### PR DESCRIPTION
**Pull request by lewisl9029**
## Summary

_This is part of a [series](https://github.com/highlight/highlight/pull/4813) [of](https://github.com/highlight/highlight/pull/4848) [PRs](https://github.com/highlight/highlight/pull/4849) [being](https://github.com/highlight/highlight/pull/4851) [spun](https://github.com/highlight/highlight/pull/4852) [off](https://github.com/highlight/highlight/pull/4907) from [my WIP branch](https://github.com/lewisl9029/highlight/pull/2) to get the Highlight web app ready for [Reflame](https://reflame.app/). Hopefully this makes things a bit easier to review, test, and merge. 🙂_ 

We had both a `CommentTextBody.module.css` and a `CommontTextBody.module.scss` previously. The scss module seems to be for regular component styling, while the css module seemed to be mostly meant to contain classes for the `@highlight-run/react-mentions` classNames prop integration.

I ended up renaming `CommentTextBody.module.css` to `mentions.module.scss` to better reflect its purpose and distinguish it from the main styling module, and so there wouldn't be any name conflicts when generating corresponding .js modules for the Reflame integration. There also seemed to be 2 classes in the css module that didn't have anything to do with mentions, so I moved those out as well.

## How did you test this change?

Tested this out in the Reflame preview:

Screenshot 2023-04-09 at 8 39 56 PM

## Are there any deployment considerations?

We do probably want to verify in Render as well to make sure Vite has the same exports output for CSS and SCSS modules.

### CODE REVIEW

**Review by Vadman97 — APPROVED** [review]

**Comment by Vadman97** [comment]
Screenshot 2023-04-09 at 8 53 36 PM

local preview looks good!

**Comment by Vadman97** [comment]
@lewisl9029 oh actually, local dev emits some typescript files that should be committed
```diff --git a/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/CommentTextBody.module.scss.d.ts b/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/CommentTextBody.module.scss.d.ts
index 4973cc9e4..471b360a1 100644
--- a/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/CommentTextBody.module.scss.d.ts
+++ b/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/CommentTextBody.module.scss.d.ts
@@ -1,7 +1,9 @@
 export const adminText: string
 export const avatarContainer: string
+export const commentText: string
 export const email: string
 export const longValue: string
+export const mentionedUser: string
 export const noResultsMessage: string
 export const slackLogo: string
 export const slackLogoContainer: string
diff --git a/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/mentions.module.scss.d.ts b/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/mentions.module.scss.d.ts
new file mode 100644
index 000000000..017a9172f
--- /dev/null
+++ b/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/mentions.module.scss.d.ts
@@ -0,0 +1,10 @@
+export const mentions: string
+export const mentionsControl: string
+export const mentionsHighlighter: string
+export const mentionsInput: string
+export const mentionsMention: string
+export const mentionsMultiLine: string
+export const mentionsSingleLine: string
+export const mentionsSuggestionsItem: string
+export const mentionsSuggestionsItemFocused: string
+export const mentionsSuggestionsList: string
```

mind adding them?

**Comment by lewisl9029** [comment]
Updated here: https://github.com/highlight/highlight/pull/4908/commits/10898b89705559458bb7716a7215b3f34f0f3198

Btw, I could never figure out what was actually generating this. 🤯

Does Vite do this by default or is it some config/plugin?

**Comment by Vadman97** [comment]
@lewisl9029 hmm, think that is a vite plugin.

looks like the build is failing now though
```Error: @highlight-run/frontend:typegen: src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/CommentTextBody.tsx(152,35): error TS2551: Property 'mentions__mention' does not exist on type 'typeof import("/home/runner/work/highlight/highlight/frontend/src/pages/Player/Toolbar/NewCommentForm/CommentTextBody/mentions.module.scss")'. Did you mean 'mentionsMention'?
@highlight-run/frontend:typegen: ERROR: command finished with error: command (/home/runner/work/highlight/highlight/frontend) yarn run typegen exited (1)
command (/home/runner/work/highlight/highlight/frontend) yarn run typegen exited (1)
```

**Comment by lewisl9029** [comment]
Ahh, seems like the generated .d.ts only includes the camelCase converted classnames, even though the actual generated module contains both that and the original __ version.

Screenshot 2023-04-10 at 1 39 51 PM

Moved it to use the camelCase name here since it doesn't really make a difference.

**Comment by Vadman97** [comment]
oh interesting, thanks @lewisl9029 !

**Pull request merged**
