### PR TITLE
fix: enabling filtering sessions without errors should have a warning callout

### LINKED ISSUE #5596: enabling filtering sessions without errors should have a warning callout
when checking the button in the `/settings` page, we should have an explicit warning modal that explains what this setting will do.

### PR DESCRIPTION
**Pull request by rishi-raj-jain**
fix #5596
/claim #5596

### CODE REVIEW

**Comment by rishi-raj-jain** [comment]
Umm okay, let me try that again. Thanks for posting the error out!

**Comment by rishi-raj-jain** [comment]
Trying to set it up succesfully... somehow all I get is that auth was not able to setup

**Comment by rishi-raj-jain** [comment]
@mayberryzane 

So I've been following: https://docs.highlight.io/docs/getting-started/self-host/dev-deployment-guide

Tried the setup 3 times already, seeing the below everytime I load up https://localhost:3000

Screenshot 2023-08-28 at 1 11 12 PM

**Comment by rishi-raj-jain** [comment]
@mayberryzane 

This is ready for review now.

**Comment by rishi-raj-jain** [comment]
image

A screenshot from my env.

**Comment by rishi-raj-jain** [comment]
Screenshot 2023-08-29 at 2 11 00 AM

Yup, I think this looks good

**Review by Vadman97 — APPROVED** [review]
🚢 thank you for your contribution!

**Pull request merged**
