### PR TITLE
Resolves issue with error monitoring inputs

### PR DESCRIPTION
**Pull request by anthonygregis**
## Summary
This resolves an issue with states being improperly updated for `Extension Error Filtering` and `Auto-Resolve Stale Errors` inside the project settings page.

Related Issue: #6631 

## How did you test this change?

Tested locally and on a self deployed version of highlight

## Are there any deployment considerations?

None, just frontend logic changes

## Does this work require review from our design team?

No

### CODE REVIEW

**Comment by anthonygregis** [comment]
Tested both locally and in a self deployed environment and can confirm both are working as expected with changes. You can now flip both toggles and save changes successfully.

If you flip the toggle of Auto-Resolve setting it will default to 1 day as to match the dropdown default setting

**Comment by Vadman97** [comment]
@anthonygregis linter seems to be failing
```
[warn] frontend/src/pages/ProjectSettings/AutoresolveStaleErrorsForm/AutoresolveStaleErrorsForm.tsx
[warn] frontend/src/pages/ProjectSettings/FilterExtensionForm/FilterExtensionForm.tsx
[warn] Code style issues found in 2 files. Forgot to run Prettier?
```
could you run `yarn format:all`?

**Comment by anthonygregis** [comment]
Sorry about that, will run and push up

**Review by mayberryzane — APPROVED** [review]
:+1: looks good in preview

**Pull request merged**
