### PR TITLE
Cleaning up Next.js quickstart

### LINKED ISSUE #5328: Revamp old NextJS quickstart wrt/ bigger guide

### PR DESCRIPTION
**Pull request by deltaepsilon**
closes #5328 

image

### CODE REVIEW

**Review by jay-khatri — APPROVED** [review]
The `HighlightInit` component is so cool. One question; should we add something here to make it clear about how to import `H`?

image

One thing I would also confirm is that this looks fine on the setup page (i.e. https://app.highlightio/setup)

**Comment by deltaepsilon** [comment]
> The `HighlightInit` component is so cool. One question; should we add something here to make it clear about how to import `H`?
> 
> image
> One thing I would also confirm is that this looks fine on the setup page (i.e. https://app.highlightio/setup)

@jay-khatri How does this look?

image

**Comment by jay-khatri** [comment]
> > The `HighlightInit` component is so cool. One question; should we add something here to make it clear about how to import `H`?
> > image
> > One thing I would also confirm is that this looks fine on the setup page (i.e. https://app.highlightio/setup)
> 
> @jay-khatri How does this look?
> 
> image

looks great.

**Comment by deltaepsilon** [comment]
image

**Comment by jay-khatri** [comment]
> image

For the first point, can we just say something like "For Next.js app directory support, session replay, the vercel log drain and non-vercel error monitoring are supported. Supporting the edge runtime and Vercel error monitoring is still wip."

Its pretty long at the moment and I'm not sure that people really need to know about specifics.

**Pull request merged**
