### PR TITLE
fix: data picker date range selection is not working on the logs page #6490

### LINKED ISSUE #6490: data picker date range selection is not working on the logs page
picker not accessible on the logs page
https://www.loom.com/share/e9760ad572324572b5e70bcb1c424d4a

### PR DESCRIPTION
**Pull request by AyushAgrawal-A2**
/claim #6490 
closes #6490 

## Summary

Added local state dateRange for date selection, this is similar to implementaion in QueryBuilder component used for other pages.

## How did you test this change?
Tested in local build. Works as expected. Screencast:-
[Screencast from 2023-09-06 22-56-29.webm](https://github.com/highlight/highlight/assets/54364088/9e848f46-3bbf-41f6-8e89-786989bbfe11)

## Are there any deployment considerations?
N/A

### CODE REVIEW

**Comment by deltaepsilon** [comment]
Great work @AyushAgrawal-A2! Click test checks out. I'm approving and we'll get this deployed.

**Review by Vadman97 — APPROVED** [review]
nice! this is working great

**Comment by Vadman97** [comment]
@AyushAgrawal-A2 mind fixing the merge conflict?

**Comment by AyushAgrawal-A2** [comment]
> @AyushAgrawal-A2 mind fixing the merge conflict?

@Vadman97 done

**Comment by AyushAgrawal-A2** [comment]
@Vadman97 please authorize "Vercel – highlight-landing"
I have resolved merge conflicts twice since PR. I am worried another merge conflict will occur again delaying the merge.

**Pull request merged**
