### PR TITLE
Typescript 5.1.0 upgrade for frontend

### PR DESCRIPTION
**Pull request by lewisl9029**
## Summary

I noticed that import specifiers of the form `@/../../packages/ui/src` were sneaking into the code and breaking Reflame deploys. I figured nobody in their right mind would manually write an import statement like this, so it must be coming from auto import. Was able to verify this:

Screenshot 2023-05-05 at 9 09 13 AM

We already had the `non-relative` import specifier setting in our VSCode config, so this shouldn't be happening. Turns out this was a Typescript bug that was very recently fixed in https://github.com/microsoft/TypeScript/pull/53957

I took this chance to upgrade us to the latest typescript 5.1.0-dev build that included this change (5.1.0-beta didn't include this unfortunately), and configure VSCode to use this build instead of its built in version, which fixed the issue:

Screenshot 2023-05-05 at 9 08 36 AM

A few other new errors showed up after the upgrade as well, so I added some quick workarounds for them too.

Note that this only upgrades us to 5.1.0 in the frontend package and project root (version used by vscode). The rest are still left as is to minimize scope. This might result in errors that show up in VSCode but not in `yarn tsc` or vice versa. Though this was already the case previously since the latest built-in Typescript version was 5.0.4, and all of our packages were on 4.x.x.

We should look into converging every package onto a single typescript version going forward.

## How did you test this change?

Tried to auto import `Box`, resulted in `@highlight-run/ui` as the top suggestion.

Ran `yarn tsc` in frontend. No errors remaining.

### CODE REVIEW

**Review by Vadman97 — APPROVED** [review]
thank you!

**Comment by Vadman97** [comment]
```
@highlight-run/rrweb-player:build: 
@highlight-run/rrweb-player:build: src/main.ts → dist/index.mjs...
@highlight-run/rrweb-player:build: rpt2: options error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
@highlight-run/rrweb-player:build:   Use 'verbatimModuleSyntax' instead.
@highlight-run/rrweb-player:build: error TS5101: Option 'importsNotUsedAsValues' is deprecated and will stop functioning in TypeScript 5.5. Specify compilerOption '"ignoreDeprecations": "5.0"' to silence this error.
@highlight-run/rrweb-player:build:   Use 'verbatimModuleSyntax' instead.
@highlight-run/rrweb-player:build: 
@highlight-run/rrweb-player:build: [!] (plugin svelte) Error: [svelte-preprocess] Encountered type error
@highlight-run/rrweb-player:build: src/Player.svelte
@highlight-run/rrweb-player:build: Error: [svelte-preprocess] Encountered type error
@highlight-run/rrweb-player:build:     at throwError (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/modules/errors.js:5:11)
@highlight-run/rrweb-player:build:     at throwTypescriptError (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/modules/errors.js:9:28)
@highlight-run/rrweb-player:build:     at transpileTs (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/transformers/typescript.js:177:47)
@highlight-run/rrweb-player:build:     at mixedImportsTranspiler (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/transformers/typescript.js:232:60)
@highlight-run/rrweb-player:build:     at transformer (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/transformers/typescript.js:302:11)
@highlight-run/rrweb-player:build:     at transform (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/autoProcess.js:37:12)
@highlight-run/rrweb-player:build:     at /home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/autoProcess.js:118:29
@highlight-run/rrweb-player:build:     at script (/home/runner/work/highlight/highlight/node_modules/svelte-preprocess/dist/autoProcess.js:148:33)
@highlight-run/rrweb-player:build:     at process_single_tag (/home/runner/work/highlight/highlight/node_modules/svelte/src/compiler/preprocess/index.ts:163:21)
@highlight-run/rrweb-player:build:     at async Promise.all (index 0)
@highlight-run/rrweb-player:build: 
@highlight-run/rrweb-player:build: ERROR: command finished with error: command (/home/runner/work/highlight/highlight/rrweb/packages/rrweb-player) yarn run build exited (1)
@highlight-run/node:typegen: cache miss, executing 2b7c9d3052fdb3e7
```

looks like the typescript version in rrweb got bumped indirectly as well. let me see if i can pin it there.

**Comment by lewisl9029** [comment]
Just saw the build failures. Opening a PR in highlight/rrweb to address them.

**Comment by Vadman97** [comment]
you'll need to update the rrweb submodule to your new commit in master and commit that here @lewisl9029

**Comment by lewisl9029** [comment]
Ah yep when I tried that I discovered I had the dependencies order wrong. Need to get this fix merged first: https://github.com/highlight/rrweb/pull/105 @Vadman97

**Comment by lewisl9029** [comment]
Alright looks like we're good to go @Vadman97

**Pull request merged**
