### PR TITLE
Disable dev tools in live mode

### PR DESCRIPTION
**Pull request by ccschmitz**
## Summary

* Replaces the dev tools with a callout explaining that dev tools can't be used in live mode
* Fixes some fetching logic when transitioning in/out of live mode
* Cleans up an unused replayer action
* Fixes display of the last activity time when using live mode
* Fixes an issue where users saw `undefined x undefined` for the dimensions of a session
* Updates the controls + activity timeline in live mode, disabling the histogram and preventing the bottom panel from jumping around when toggling live mode
* Fixes secondary medium emphasis tag backgrounds

Screenshot 2023-06-22 at 9 57 46 AM

## How did you test this change?

Local and PR preview click test.

## Are there any deployment considerations?

N/A

### CODE REVIEW

**Review by Vadman97 — APPROVED** [review]
preview looks great!
should we also auto-close the dev tools when you click `Show live mode`? seems annoying to have that space taken up by the new card when the intention might be to close the dev tools anyways

**Comment by ccschmitz** [comment]
@Vadman97 I did consider closing them automatically, but I didn't like that it changed the view on you when you toggled it back off. Thinking about this more, I think I'll actually have it behave exactly like the timeline, but I'm going to keep the icons on the right-hand side visible, disable them, and update the tooltip contents to explain they aren't available in live mode.

@julian-highlight @jay-khatri is that cool with you?

**Comment by ccschmitz** [comment]
After [further discussion w/ Julian](https://highlightcorp.slack.com/archives/C01FJL7V630/p1686320044040729), we are going to make some updates to this. See Figma for the latest mocks: https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=5407%3A242453&t=oCqvJ96PMxlMecS4-1

**Comment by ccschmitz** [comment]
@Vadman97 would you mind giving this one another look? I had a bunch of back and forth with @julian-highlight on the UI so I've made a lot of revisions. Would appreciate another review whenever you have time!

**Review by Vadman97 — APPROVED** [review]
click tested, all the improvements look great. watching my own live session feels snappier too somehow (live event updates seem to be coming thru faster)

**Pull request merged**
