### PR TITLE
Customer page bugs

### PR DESCRIPTION
**Pull request by Abhishek-More**
## Summary
Customer images on /customers are flickering on refresh.
Additionally, the mobile view is shown on desktop for each individual testimonial

## How did you test this change?

Click-testing
https://highlight-landing-n4dzuxjfm-highlight-run.vercel.app/customers

## Are there any deployment considerations?

No

## Does this work require review from our design team?

No

### CODE REVIEW

**Review by Vadman97 — CHANGES_REQUESTED** [review]
strange, the images are entirely blank for me

Screenshot from 2023-12-19 15-05-53

**Comment by Abhishek-More** [comment]
Yeah, it looks like its not working in Chrome, while Firefox and Arc work fine. It may have something to do with the way onLoad works in Chrome. Working on a fix now.

**Comment by Abhishek-More** [comment]
@Vadman97 Should be fixed now. Had to switch from onLoad to onLoadingComplete. Even though the latter was recently deprecated, I guess onLoad is not supported for remote images on Chrome yet.

**Review by Vadman97 — APPROVED** [review]
nice, looks great now!

**Pull request merged**
