### PR TITLE
Pin react-resize-aware to 3.1.0

### PR DESCRIPTION
**Pull request by lewisl9029**
## Summary

3.1.2 seems to have a broken build that references jsx without importing react: https://github.com/FezVrasta/react-resize-aware/issues/58

Pinning to the current version in the lockfile so there's no room for deviation in Reflame deploys.

### CODE REVIEW

**Review by Vadman97 — APPROVED** [review]
thanks for catching this @lewisl9029 ! think i noticed this one today in a preview

**Comment by Vadman97** [comment]
Screenshot 2023-07-11 at 10 17 55 PM
@lewisl9029 checking the reflame preview, seems to break when i view an error (ie https://preview.highlight.io/1/errors/c39utTDGLfDwLQmjds0m1NteSfcA?page=1&query=and%7C%7Cerror_state%2Cis%2COPEN%7C%7Cerror-field_timestamp%2Cbetween_date%2C2023-06-12T05%3A17%3A37.577Z_2023-07-12T05%3A17%3A37.577Z&%7Er_preview=%7B%22action%22%3A%22start%22%2C%22mode%22%3A%22production%22%2C%22region%22%3A%22sjc%22%2C%22variantId%22%3A%2201H548FPGFBKF1FFESDPZP3ZWY%22%2C%22variantData%22%3A%22%7B%5C%22type%5C%22%3A%5C%22branch%5C%22%2C%5C%22branch%5C%22%3A%5C%22pin-react-resize-aware%5C%22%2C%5C%22forkSpecifier%5C%22%3A%5C%22lewisl9029%2Fhighlight%5C%22%2C%5C%22githubOwnerName%5C%22%3A%5C%22highlight%5C%22%2C%5C%22githubRepositoryName%5C%22%3A%5C%22highlight%5C%22%7D%22%7D)

**Comment by lewisl9029** [comment]
Oh no, taking a look.

**Comment by lewisl9029** [comment]
So this actually has to do with our lack of proper support for [analyzing exports on minified UMD modules](https://twitter.com/lewisl9029/status/1674658088090210304).
I pushed a [temporary workaround](https://github.com/highlight/highlight/pull/5879/commits/78744c26c2161ecb8991d2c59a463309fa515d4e) to unbreak the build. Going to try to get this fixed properly tomorrow.

**Comment by Vadman97** [comment]
🙏 reflame preview looks good now. thanks @lewisl9029 !

**Comment by lewisl9029** [comment]
@Vadman97 sorry looks like there was a bug in my workaround for the Vite build, good thing the tests caught it 😌 
Should be good to go this time. 🙏

**Comment by lewisl9029** [comment]
Hmm any ideas what this error is about:

**Comment by Vadman97** [comment]
taking a look @lewisl9029 , looks like a new check i've added doesn't work in forks 🤦

**Pull request merged**
