### PR TITLE
Added sidebar to workspace & account settings

### PR DESCRIPTION
**Pull request by eightants**
## Summary

Initial work on implementing the new settings page from https://github.com/highlight/highlight/issues/4917. Since the new settings layout consolidates all 3 types of settings on one page, and also changes the content of some pages, this might be best done in a few stages for easy PR review. This PR adds the sidebar as shown in the Figma, and consolidates account and workspace settings on the same page. 

## How did you test this change?

Screenshot 2023-04-24 at 11 34 26 AM

## Are there any deployment considerations?

NA

### CODE REVIEW

**Comment by jay-khatri** [comment]
Couple things to keep in mind here, as you build this out:
- There's a random flash of a white screen when going from the main app (e.g. app.highlight.io/sessions) to workspace settings. Try to take a look at make sure this is fixed as you roll these changes out?
- We should make sure that links don't break, as we use these links in our docs and callouts throughout the app.

**Review by mayberryzane — APPROVED** [review]
Code looks good to me pending design review from Julian!

**Comment by jay-khatri** [comment]
@julian-highlight do we want to show the top right nav items in this view? In the setup view, we don't show them. we should be consistent?

**Comment by julian-highlight** [comment]
@jay-khatri No you're right! Let's not show these here, just like in the setup flow! 
CC @eightants

**Comment by jay-khatri** [comment]
Ok, @eightants, I put a few bullet points (including this one) to address on this ticket: https://github.com/highlight/highlight/issues/4917

**Pull request merged**
