### PR TITLE
Publish codegen blog post

### PR DESCRIPTION
**Pull request by ccschmitz**
## Summary

Publishes a blog post on leveraging codegen to speed up development. Original source [in Notion](https://www.notion.so/runhighlight/Supercharge-Your-Development-Workflow-with-Code-Generators-be35270106174f2fac65b5e0921a556e?pvs=4).

- [ ] Add code snippets from our codebase
- [ ] Add section on the future of codegen w/ AI

## How did you test this change?

Local click test. Should also be available in the Vercel preview.

## Are there any deployment considerations?

N/A

### CODE REVIEW

**Comment by ccschmitz** [comment]
@jay-khatri think I should add something about AI? e.g. how to use ChatGPT or Copilot for generating code?

**Comment by jay-khatri** [comment]
Sorry that I missed this. Just read the article and it looks awesome. For the examples of using code gen in our codebase, it could be cool to add code snippets of where/how these libraries are used 🤔 , i.e. an example of the generated hook from graphql-codegen. 

Re: chatgpt, that could be cool. What did you have in mind? One part of me thinks that. the use of ChatGPT might be a bit tangential since its not really structured codegen. But it can't hurt to talk about it at the end alluding to the future of codegen being driven by AI or something?

**Review by jay-khatri — APPROVED** [review]

**Review by Abhishek-More — APPROVED** [review]

**Comment by Vadman97** [comment]
should we merge this @ccschmitz ?

**Comment by ccschmitz** [comment]
@jay-khatri @Vadman97 just added tightened this up and added a section on using AI. Set to merge after another approval - would you mind giving it a final review sometime?

**Review by Vadman97 — APPROVED** [review]
thanks @ccschmitz , looking groovy 🚢

**Pull request merged**
