### PR TITLE
feat: jump into timestamp directly

### PR DESCRIPTION
**Pull request by neo773**
This PR adds ability to jump directly to a timestamp without opening the Event details

https://github.com/highlight/highlight/assets/62795688/caeccef8-4ccd-4172-a67f-b23f942b1654

/claim #6277

### CODE REVIEW

**Comment by Vadman97** [comment]
Hey @neo773 , this is already being implemented in #6418. There are new designs ([see figma](https://www.figma.com/file/rdBPNzn7Klk6RG1LHUCE5B/Screen-Designs?type=design&node-id=4451%3A207492&mode=design&t=CiOZjQGiRX6N4i9M-1)) for the goto timestamp button.

**Comment by neo773** [comment]
@Vadman97 Fixed the search state not being preserved

**Comment by rishi-raj-jain** [comment]
Can someone help me run the frontend succesfully?

https://github.com/highlight/highlight/pull/6419#issuecomment-1695192865 is the issue I'm facing.

**Comment by rishi-raj-jain** [comment]
https://discord.com/channels/1026884757667188757/1078929798828666981/1145743559513870447 discord message.

**Comment by neo773** [comment]
> Implemented in #6418
> In the future, we will only award the bounty to the first person to claim and start working on a task.
> Since we were not clear about this policy this time, I'm offering a part of the bounty for your help.
> /tip $25

Agreed, I was the first one to attempt the bounty

**Pull request closed without merging**
