### PR TITLE
Adding java framework sping web

### PR DESCRIPTION
**Pull request by NgLoader**
## Summary
Just adding a java framework named ``spring``.
More information will follow.

Issue: #4364

### CODE REVIEW

**Review by Vadman97 — APPROVED** [review]
looks good so far! is this ready to merge @NgLoader ?

**Comment by Vadman97** [comment]
Bump here @NgLoader

**Comment by NgLoader** [comment]
> Bump here @NgLoader

Hey, I'm going to add some commits for the spring implementation this weeks soon.

**Comment by Vadman97** [comment]
hey @NgLoader , any chance to update this?

**Pull request closed without merging**
