### PR TITLE
Add errors tab to network request details panel

### PR DESCRIPTION
**Pull request by ccschmitz**
## Summary

Adds an Errors tab to the network request detail panel which shows a list of errors associated with the request.

Screenshot 2023-07-12 at 3 19 52 PM

## How did you test this change?

Local click test.

## Are there any deployment considerations?

N/A

### CODE REVIEW

**Comment by jay-khatri** [comment]
Sorry for the comment out of nowhere. Quick thought. the "Network Request" text here is awkwardly close to the line above it 🤔 . I'm seeing int he designs that there's a bit more space maybe?
image

**Comment by ccschmitz** [comment]
> Sorry for the comment out of nowhere. Quick thought. the "Network Request" text here is awkwardly close to the line above it 🤔 . I'm seeing int he designs that there's a bit more space maybe?

@jay-khatri yeah, I see what you mean. Not sure how I messed that up initially, but just cleaned it up in https://github.com/highlight/highlight/pull/5893/commits/6da629588473bcd8aa81725199a017ae1c7767a8.

**Review by et — COMMENTED** [review]
I'm having trouble finding an error using prod data.
Here's a loom: https://www.loom.com/share/b991b3ced14847a28bb82f2ab2ecd1bc
and the session I was looking at: https://frontend-pr-5893.onrender.com/1/sessions/Q6ob8FWe1Sqqac2lQF6xjsEuA7ox?network-resource-id=167&page=1&query=and%7C%7Ccustom_processed%2Cis%2Ctrue%7C%7Ccustom_created_at%2Cbetween_date%2C2023-06-13T16%3A45%3A35.374Z_2023-07-13T16%3A45%3A35.374Z

@ccschmitz - can you show an example on prod that has non empty errors for a network request?

**Comment by ccschmitz** [comment]
@et thanks for click testing! Yeah, it can be kind of hard to find requests with errors, and not all requests that were unsuccessful actually have errors associated with them. We may want to think about making it possible to link to a request from an error when there is one associated with the instance (cc @jay-khatri and @julian-highlight).

Here is a link to a session with a number of errored requests that should have errors populating in the new tab: https://frontend-pr-5893.onrender.com/1/sessions/TgN8ky4ZDPckVsTlS565L5UAGlUl

**Review by et — APPROVED** [review]
Thanks for sharing that session. Was able to find a network request with an error and it works as expected.

As an aside, this "View error group" button:

Screenshot 2023-07-13 at 11 41 01 AM

should
* be a proper link (see #5868)
* link to the error instance, not just the error group

That's outside of scope of this PR. Just wanted to float that feedback if you're still working in this area.

**Comment by ccschmitz** [comment]
@et thanks for flagging that! I'm happy to push a fix for that in my next PR to add logs to the network request panel!

**Pull request merged**
