### PR TITLE
record contact info for self serve app

### PR DESCRIPTION
**Pull request by Vadman97**
## Summary

* records contact info (with ability to opt-out) for self-hosted deployments
* makes `/about_you` page fields required ( cc @jay-khatri )

## How did you test this change?

Screenshot 2023-09-19 at 1 45 01 PM

Screenshot 2023-09-19 at 1 44 40 PM

with checkbox unchecked

Screenshot 2023-09-19 at 1 45 38 PM

data stored when checked, not stored when not checked
Screenshot 2023-09-19 at 1 50 40 PM

## Are there any deployment considerations?

No

## Does this work require review from our design team?

Yes

### CODE REVIEW

**Comment by jay-khatri** [comment]
lgtm. small visual thing i noticed; there's an extra line (or a thicker line) between first and last name here: 
image

**Review by SpennyNDaJets — APPROVED** [review]
LGTM

**Review by julian-highlight — APPROVED** [review]

**Comment by Vadman97** [comment]
@jay-khatri fixed
Screenshot 2023-09-20 at 10 57 48 AM

**Comment by julian-highlight** [comment]
> @jay-khatri fixed Screenshot 2023-09-20 at 10 57 48 AM

btw this is something I've seen in other places as well (Like the date picker when adding time values for a specific day). Seems like it's fixed everywhere now?

**Pull request merged**
