### PR TITLE
Add explicit button for session summary

### PR DESCRIPTION
**Pull request by eightants**
## Summary

Added button to trigger session insights as specified in https://github.com/highlight/highlight/issues/5687

Also fixed the backend insights retry function when local server is unavailable. 

Screenshot 2023-06-27 at 12 43 11 PM

### CODE REVIEW

**Review by Vadman97 — COMMENTED** [review]
unrelated to this PR, but just noticed that insights can come out of order. can we update the prompt to fix that?

image

**Review by SpennyNDaJets — COMMENTED** [review]
Wanted to just raise the following things I found from click testing:
1. The Button is not there after generating a response, and then changing sessions. Not sure if its automatically hitting our endpoint, or stuck in a loading loop though 🤔 
2. The times seem to be off, but not sure if this is a local/unrelated issue
Screenshot 2023-06-27 at 12 53 10 PM

**Comment by eightants** [comment]
> Wanted to just raise the following things I found from click testing:
> 
> 1. The Button is not there after generating a response, and then changing sessions. Not sure if its automatically hitting our endpoint, or stuck in a loading loop though 🤔
> 2. The times seem to be off, but not sure if this is a local/unrelated issue
>    Screenshot 2023-06-27 at 12 53 10 PM

2. Yeah this is cause we're using a production session in s3 to get all session events, so the timestamps on that session doesn't match the local session

**Review by Vadman97 — CHANGES_REQUESTED** [review]
small note on the loading button
also the insights seem to be broken in the lambda
https://www.loom.com/share/14373574d53942e390988be0efd2fffa

**Review by Vadman97 — APPROVED** [review]
realized that the lambda might be broken in the render.com preview since that doesn't deploy the backend changes, in which case disregard!

**Pull request merged**
